### ISSUE TITLE
static --html generation not working in python 3.7.4?

### ISSUE THREAD

**Issue by yuselg** [HEInventions/docnado#51]
```
> python3
Python 3.7.3 (default, Jun 19 2019, 07:38:49) 

> docnado --new
this works

>docnado
 * Serving Flask app "docnado.docnado" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

> docnado --html mysite
[2019-09-18 13:01:04,112] ERROR in app: Exception on /w/setup/meta-data.md [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()

 ...
  new_filename = self._build_one(url)
  File "/usr/local/lib/python3.7/site-packages/flask_frozen/__init__.py", line 322, in _build_one
    % (response.status, url))
ValueError: Unexpected status '500 INTERNAL SERVER ERROR' on URL /w/setup/meta-data.md
```

**Comment by yuselg** [comment]
Same issue for

``>python3
Python 3.7.4 (default, Sep  7 2019, 18:27:02) 
```

**Comment by JohnHardy** [comment]
@wilad says he will try and reproduce this in the next few days

**Comment by ghost** [comment]
I'm struggling to recreate your issue. Can you please send me some details of your setup (OS/Distro, pip freeze etc) do I can try to replicate this?

Are you running the pip-version or the git version?
