### ISSUE TITLE
static --html generation not working

### ISSUE THREAD

**Issue by mnbf9rca** [HEInventions/docnado#52]
docnado doesnt build HTML output from the default/demo site contents:
Ive tried python 3.6.9, 3.7.6 and 3.8.2, all on ubuntu 18.04 LTS. All ive done is:
1. install docnado `pip install --upgrade docnado`
1. create new folder, `src` and `out`
1. change to folder `cd src`
1. initialise `docnado --new`
1. build `docnado --html ../out/`

i've tried this using ubuntu 18.04 LTS running on WSL, and on an [Azure Devops Ubuntu build pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent). In case it's more useful, here are the full [logs from our build pipeline](https://github.com/HEInventions/docnado/files/4377819/7.txt)

```
rob@Laptop:~/git/rob-test/src$ docnado --html ../out/
[2020-03-24 21:37:23,811] ERROR in app: Exception on /w/setup/meta-data.md [GET]
Traceback (most recent call last):
  File "/home/rob/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rob/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rob/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rob/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/rob/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rob/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rob/.local/lib/python3.6/site-packages/docnado/docnado.py", line 573, in wiki
    return _render_markdown(file_path, current_page=page)
  File "/home/rob/.local/lib/python3.6/site-packages/docnado/docnado.py", line 498, in _render_markdown
    **kwargs)
  File "/home/rob/.local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/rob/.local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/rob/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/rob/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/rob/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/Users/rob/Downloads/git/rob-test/src/style/templates/document.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/rob/Downloads/git/rob-test/src/style/templates/base.html", line 114, in top-level template code
    <div class="page-content">
  File "/mnt/c/Users/rob/Downloads/git/rob-test/src/style/templates/document.html", line 19, in block "content"    <small>last updated <span>{{ date | first | timesince }}</span> on <span>{{ date | first }}</span></small>
  File "/home/rob/.local/lib/python3.6/site-packages/docnado/docnado.py", line 535, in timesince
    dt = datetime.datetime.strptime(dt, '%Y/%m/%d')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 6
Traceback (most recent call last):
  File "/home/rob/.local/lib/python3.6/site-packages/docnado/docnado.py", line 1168, in main
    generate_static_html(app, dir_documents, os.path.join(os.getcwd(), args.html_output_dir))
  File "/home/rob/.local/lib/python3.6/site-packages/docnado/docnado.py", line 674, in generate_static_html
    freezer.freeze()
  File "/home/rob/.local/lib/python3.6/site-packages/flask_frozen/__init__.py", line 199, in freeze
    return set(page.url for page in self.freeze_yield())
  File "/home/rob/.local/lib/python3.6/site-packages/flask_frozen/__init__.py", line 199, in <genexpr>
    return set(page.url for page in self.freeze_yield())
  File "/home/rob/.local/lib/python3.6/site-packages/flask_frozen/__init__.py", line 183, in freeze_yield
    new_filename = self._build_one(url)
  File "/home/rob/.local/lib/python3.6/site-packages/flask_frozen/__init__.py", line 322, in _build_one
    % (response.status, url))
ValueError: Unexpected status '500 INTERNAL SERVER ERROR' on URL /w/setup/meta-data.md
```

**Comment by JohnHardy** [comment]
Hi Rob,

Thanks for reporting the problem and the great description.

I saw that you used the `--new` flag, but please could you double check the documents all have a `date` field with data in the format: `YYYY/MM/DD`  https://heinventions.github.io/docnado-site/example-site/w/setup/meta-data.html

It may take me a little while to get to this with what is going on at the moment!

Cheers,
John

**Comment by ghost** [comment]
Hi mnbf9rca,
I've had a look at this issue today. I performed the following steps on Ubuntu 18.04 LTS with Python 3.6.9 :
1. Install docnado with "pip3 install docnado".
2. make the to directories (mkdir src; mkdir out).
3. Change to the "src" directory, create a new docnado project (cd src; docnado --new).
4. Rendered the docnado sample project to static html with "docnado --html ../out/"

Everything worked as expected and I was unable to reproduce your bug. I don't currently have acces to an Azure Devops server to test more closely to your target platform. Any further details you could give me would be greatly appreciated.

It looks like you're having some issues with the datetime functionality. Can you try running that in isolation? Does running the the first example on [this page](https://www.programiz.com/python-programming/datetime/strptime) sucessfully run?
